// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: models/wallet_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation_OperationType int32

const (
	Operation_OPERATION_TYPE_UNSPECIFIED Operation_OperationType = 0
	Operation_DEPOSIT                    Operation_OperationType = 1
	Operation_WITHDRAW                   Operation_OperationType = 2
)

// Enum value maps for Operation_OperationType.
var (
	Operation_OperationType_name = map[int32]string{
		0: "OPERATION_TYPE_UNSPECIFIED",
		1: "DEPOSIT",
		2: "WITHDRAW",
	}
	Operation_OperationType_value = map[string]int32{
		"OPERATION_TYPE_UNSPECIFIED": 0,
		"DEPOSIT":                    1,
		"WITHDRAW":                   2,
	}
)

func (x Operation_OperationType) Enum() *Operation_OperationType {
	p := new(Operation_OperationType)
	*p = x
	return p
}

func (x Operation_OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation_OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_wallet_model_proto_enumTypes[0].Descriptor()
}

func (Operation_OperationType) Type() protoreflect.EnumType {
	return &file_models_wallet_model_proto_enumTypes[0]
}

func (x Operation_OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation_OperationType.Descriptor instead.
func (Operation_OperationType) EnumDescriptor() ([]byte, []int) {
	return file_models_wallet_model_proto_rawDescGZIP(), []int{1, 0}
}

type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_models_wallet_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_models_wallet_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_models_wallet_model_proto_rawDescGZIP(), []int{0}
}

func (x *Wallet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wallet) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type Operation struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	WalletId      string                  `protobuf:"bytes,1,opt,name=walletId,proto3" json:"walletId,omitempty"`
	OperationType Operation_OperationType `protobuf:"varint,2,opt,name=operationType,proto3,enum=walletservice.models.v1.Operation_OperationType" json:"operationType,omitempty"`
	Amount        int64                   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_models_wallet_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_models_wallet_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_models_wallet_model_proto_rawDescGZIP(), []int{1}
}

func (x *Operation) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *Operation) GetOperationType() Operation_OperationType {
	if x != nil {
		return x.OperationType
	}
	return Operation_OPERATION_TYPE_UNSPECIFIED
}

func (x *Operation) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_models_wallet_model_proto protoreflect.FileDescriptor

const file_models_wallet_model_proto_rawDesc = "" +
	"\n" +
	"\x19models/wallet_model.proto\x12\x17walletservice.models.v1\"2\n" +
	"\x06Wallet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\"\xe3\x01\n" +
	"\tOperation\x12\x1a\n" +
	"\bwalletId\x18\x01 \x01(\tR\bwalletId\x12V\n" +
	"\roperationType\x18\x02 \x01(\x0e20.walletservice.models.v1.Operation.OperationTypeR\roperationType\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"J\n" +
	"\rOperationType\x12\x1e\n" +
	"\x1aOPERATION_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aDEPOSIT\x10\x01\x12\f\n" +
	"\bWITHDRAW\x10\x02B7Z5github.com/J0hnLenin/WalletService/internal/pb/modelsb\x06proto3"

var (
	file_models_wallet_model_proto_rawDescOnce sync.Once
	file_models_wallet_model_proto_rawDescData []byte
)

func file_models_wallet_model_proto_rawDescGZIP() []byte {
	file_models_wallet_model_proto_rawDescOnce.Do(func() {
		file_models_wallet_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_wallet_model_proto_rawDesc), len(file_models_wallet_model_proto_rawDesc)))
	})
	return file_models_wallet_model_proto_rawDescData
}

var file_models_wallet_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_models_wallet_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_models_wallet_model_proto_goTypes = []any{
	(Operation_OperationType)(0), // 0: walletservice.models.v1.Operation.OperationType
	(*Wallet)(nil),               // 1: walletservice.models.v1.Wallet
	(*Operation)(nil),            // 2: walletservice.models.v1.Operation
}
var file_models_wallet_model_proto_depIdxs = []int32{
	0, // 0: walletservice.models.v1.Operation.operationType:type_name -> walletservice.models.v1.Operation.OperationType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_models_wallet_model_proto_init() }
func file_models_wallet_model_proto_init() {
	if File_models_wallet_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_wallet_model_proto_rawDesc), len(file_models_wallet_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_wallet_model_proto_goTypes,
		DependencyIndexes: file_models_wallet_model_proto_depIdxs,
		EnumInfos:         file_models_wallet_model_proto_enumTypes,
		MessageInfos:      file_models_wallet_model_proto_msgTypes,
	}.Build()
	File_models_wallet_model_proto = out.File
	file_models_wallet_model_proto_goTypes = nil
	file_models_wallet_model_proto_depIdxs = nil
}
