// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: wallets_api/wallets.proto

package wallets_api

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	models "github.com/J0hnLenin/WalletService/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_wallets_api_wallets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallets_api_wallets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_wallets_api_wallets_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_wallets_api_wallets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallets_api_wallets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_wallets_api_wallets_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_wallets_api_wallets_proto protoreflect.FileDescriptor

const file_wallets_api_wallets_proto_rawDesc = "" +
	"\n" +
	"\x19wallets_api/wallets.proto\x12\x18walletservice.service.v1\x1a\x19models/wallet_model.proto\x1a\x1cgoogle/api/annotations.proto\"0\n" +
	"\x11GetBalanceRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"=\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x83\x02\n" +
	"\x0eWalletsService\x12p\n" +
	"\x0eApplyOperation\x12\".walletservice.models.v1.Operation\x1a\x1f.walletservice.models.v1.Wallet\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/wallet\x12\x7f\n" +
	"\n" +
	"GetBalance\x12+.walletservice.service.v1.GetBalanceRequest\x1a\x1f.walletservice.models.v1.Wallet\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/wallets/{wallet_id}B<Z:github.com/J0hnLenin/WalletService/internal/pb/wallets_apib\x06proto3"

var (
	file_wallets_api_wallets_proto_rawDescOnce sync.Once
	file_wallets_api_wallets_proto_rawDescData []byte
)

func file_wallets_api_wallets_proto_rawDescGZIP() []byte {
	file_wallets_api_wallets_proto_rawDescOnce.Do(func() {
		file_wallets_api_wallets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallets_api_wallets_proto_rawDesc), len(file_wallets_api_wallets_proto_rawDesc)))
	})
	return file_wallets_api_wallets_proto_rawDescData
}

var file_wallets_api_wallets_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wallets_api_wallets_proto_goTypes = []any{
	(*GetBalanceRequest)(nil), // 0: walletservice.service.v1.GetBalanceRequest
	(*ErrorResponse)(nil),     // 1: walletservice.service.v1.ErrorResponse
	(*models.Operation)(nil),  // 2: walletservice.models.v1.Operation
	(*models.Wallet)(nil),     // 3: walletservice.models.v1.Wallet
}
var file_wallets_api_wallets_proto_depIdxs = []int32{
	2, // 0: walletservice.service.v1.WalletsService.ApplyOperation:input_type -> walletservice.models.v1.Operation
	0, // 1: walletservice.service.v1.WalletsService.GetBalance:input_type -> walletservice.service.v1.GetBalanceRequest
	3, // 2: walletservice.service.v1.WalletsService.ApplyOperation:output_type -> walletservice.models.v1.Wallet
	3, // 3: walletservice.service.v1.WalletsService.GetBalance:output_type -> walletservice.models.v1.Wallet
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wallets_api_wallets_proto_init() }
func file_wallets_api_wallets_proto_init() {
	if File_wallets_api_wallets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallets_api_wallets_proto_rawDesc), len(file_wallets_api_wallets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallets_api_wallets_proto_goTypes,
		DependencyIndexes: file_wallets_api_wallets_proto_depIdxs,
		MessageInfos:      file_wallets_api_wallets_proto_msgTypes,
	}.Build()
	File_wallets_api_wallets_proto = out.File
	file_wallets_api_wallets_proto_goTypes = nil
	file_wallets_api_wallets_proto_depIdxs = nil
}
