// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/J0hnLenin/WalletService/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// WalletStorage is an autogenerated mock type for the WalletStorage type
type WalletStorage struct {
	mock.Mock
}

// ApplyOperation provides a mock function with given fields: ctx, op
func (_m *WalletStorage) ApplyOperation(ctx context.Context, op *models.WalletOperation) error {
	ret := _m.Called(ctx, op)

	if len(ret) == 0 {
		panic("no return value specified for ApplyOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.WalletOperation) error); ok {
		r0 = rf(ctx, op)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWalletByID provides a mock function with given fields: ctx, id
func (_m *WalletStorage) GetWalletByID(ctx context.Context, id uuid.UUID) (*models.Wallet, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletByID")
	}

	var r0 *models.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Wallet, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Wallet); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWalletStorage creates a new instance of WalletStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletStorage {
	mock := &WalletStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
